[project]
name = "smart-home"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "colour>=0.1.5",
    "flask>=3.1.2",
    "pywizlight>=0.6.3",
]
